### ISSUE TITLE
Windows storage corruption

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/bitcoinX#13]
We have a rare but continually occurring problem where users on Windows are getting corrupt header files. This is a tracking issue where we can attempt to analyse the problem and diagnose a cause.

**Comment by rt121212121** [comment]
Reproduction 2022-11-01
=================

Analysis
---------

Looking at the attached headers file, it can be seen that there is a corrupt header entry. An older header (height 760156, hash `0000000000000000040299553e928fcf7923d0cfad1cc7a2a946afab205811ac`) is duplicated in place of a later header (height 761912, hash `000000000000000002c1fa61e47af3f6b1dc877fd9dedd82c9033452d76c6c52`), and when the next later header (height 761913, hash `0000000000000000055936f0af59b7a05b6b234b72d6ecbe5bd592470715eaa4`) is processed it cannot find the preceding header (the height 761912, hash `000000000000000002c1fa61e47af3f6b1dc877fd9dedd82c9033452d76c6c52`) entry because of this.

Printing out the header hashes nearing the point of failure and their index in the attached `headers` file:

```
Index     Height   Hash
760159  760156  0000000000000000040299553e928fcf7923d0cfad1cc7a2a946afab205811ac
761914  761911  000000000000000008fb7ef62c1d61890fba6a8188b9216b21ea9cde385c7ac4
761915  760156  0000000000000000040299553e928fcf7923d0cfad1cc7a2a946afab205811ac
761916  761913  0000000000000000055936f0af59b7a05b6b234b72d6ecbe5bd592470715eaa4
```

The conclusion here is that somehow the header at height 761912  was somehow not written and it was replaced with the older header.

Looking at ElectrumSV:

Incoming headers are passed to bitcoinx through two mechanisms, `set_one` and `connect`. `set_one` only works near the checkpoint and the checkpoint is height 646575, and this rules out ElectrumSV calling `set_one` incorrectly. `connect` checks if the header being connected and returns it if it is already present (which the duplicate header would be). It does not appear possible for ElectrumSV to be doing something incorrectly here.

Outstanding thoughts:

In order for 761913 to be connected, 761912 had to be present in memory and an attempt had to have been made to write it to the storage when 761912 was connected.

Software versions
-------------------

* ElectrumSV 1.3.13.
* bitcoinX 0.2.4.

Exception traceback
----------------------

From `-v=debug` in a cmd window:
```
Traceback (most recent call last):
  File "electrum-sv", line 36, in <module>
  File "electrumsv\main.py", line 432, in main
  File "electrumsv\main.py", line 262, in run_app_with_daemon
  File "electrumsv\daemon.py", line 157, in __init__
  File "electrumsv\network.py", line 900, in __init__
  File "electrumsv\app_state.py", line 104, in read_headers
  File "site-packages\bitcoinx\chain.py", line 386, in from_file
  File "site-packages\bitcoinx\chain.py", line 321, in __init__
  File "site-packages\bitcoinx\chain.py", line 360, in _read_headers
  File "site-packages\bitcoinx\chain.py", line 367, in _read_header
  File "site-packages\bitcoinx\chain.py", line 419, in lookup
  File "site-packages\bitcoinx\chain.py", line 353, in _header_index_slow
bitcoinx.chain.MissingHeader: no header with hash 000000000000000002c1fa61e47af3f6b1dc877fd9dedd82c9033452d76c6c52
```

Relevant files
---------------

[headers.zip](https://github.com/kyuupichan/bitcoinX/files/9932603/headers.zip)

**Comment by rmtew** [comment]
Here is a different issue, "no header at index". Unfortunately I didn't get headers files from these users because I was not thinking.

From ElectrumSV 1.3.11:

![image](https://user-images.githubusercontent.com/1057638/199826940-022223a5-2c67-4379-9cba-ae06811c45b4.png)

From ElectrumSV 1.2.5:

```
Traceback (most recent call last):
File "electrum-sv", line 36, in
File "electrumsv\main.py", line 414, in main
File "electrumsv\main.py", line 266, in run_app_with_daemon
File "electrumsv\daemon.py", line 145, in init
File "electrumsv\network.py", line 901, in init
File "electrumsv\app_state.py", line 90, in read_headers
File "site-packages\bitcoinx\chain.py", line 386, in from_file
File "site-packages\bitcoinx\chain.py", line 321, in init
File "site-packages\bitcoinx\chain.py", line 360, in _read_headers
File "site-packages\bitcoinx\chain.py", line 366, in _read_header
File "site-packages\bitcoinx\chain.py", line 256, in getitem
File "site-packages\bitcoinx\chain.py", line 250, in header
bitcoinx.chain.MissingHeader: no header at index 630865
```

There's another ElectrumSV issue which has [a headers file](https://github.com/electrumsv/electrumsv/issues/132) but no details.

From ElectrumSV 1.2.1:

```
Traceback (most recent call last):
File "electrum-sv", line 36, in
File "electrumsv\main.py", line 407, in main
File "electrumsv\main.py", line 267, in run_app_with_daemon
File "electrumsv\daemon.py", line 135, in init
File "electrumsv\network.py", line 823, in init
File "electrumsv\app_state.py", line 73, in read_headers
File "site-packages\bitcoinx\chain.py", line 386, in from_file
File "site-packages\bitcoinx\chain.py", line 321, in init
File "site-packages\bitcoinx\chain.py", line 360, in _read_headers
File "site-packages\bitcoinx\chain.py", line 366, in _read_header
File "site-packages\bitcoinx\chain.py", line 256, in getitem
File "site-packages\bitcoinx\chain.py", line 250, in header
bitcoinx.chain.MissingHeader: no header at index 579155
```

**Comment by rt121212121** [comment]
Report of corrupted storage on Linux.
https://github.com/electrumsv/electrumsv/issues/1016

**Comment by kyuupichan** [comment]
I'll close this as the code is being removed
